<template>
  <div style="justify-content: center; align-items: center">
    <div style="align-items: center; justify-content: center">
      <h1>This is an about page</h1>
    </div>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse in cursus urna, eu euismod mi. Vivamus ut sapien mauris. Fusce id faucibus odio. In vitae diam magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec euismod nibh eu enim aliquam convallis. Donec ut ornare est.

      Nam pellentesque, leo at tincidunt pulvinar, nunc eros imperdiet ex, vitae sagittis neque nunc ut urna. Fusce venenatis, lacus sed maximus laoreet, elit enim feugiat purus, id consectetur nulla turpis eu erat. Pellentesque lorem nulla, vestibulum ac finibus vitae, lacinia ut massa. Fusce non cursus eros, ac feugiat justo. Nulla nulla enim, efficitur in sollicitudin vulputate, dapibus id risus. Mauris dapibus arcu eu ante facilisis porta. Aliquam malesuada massa lectus, sit amet fermentum dolor pellentesque et. Quisque elementum nisi ut lectus lobortis pellentesque. Etiam sit amet mattis sem. Integer lacinia rhoncus dui, a ultricies sapien semper lobortis. Suspendisse sit amet venenatis est, et auctor magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum laoreet mauris a euismod condimentum. Nam dapibus pharetra neque, vitae vehicula ligula lacinia nec. Quisque elit risus, venenatis rutrum vehicula sit amet, hendrerit ultrices enim. Cras sed mauris eget est porttitor faucibus vitae faucibus elit.

      Nulla tempor leo nibh, quis suscipit dolor suscipit at. Nam rutrum, lectus at sodales dapibus, lectus ante tincidunt erat, quis fermentum arcu lacus ac tortor. Nullam vehicula nulla libero, a facilisis ex commodo at. Cras nulla arcu, varius et lacus sed, varius iaculis turpis. Integer elit nisi, malesuada ut interdum eget, vestibulum feugiat purus. Cras tempor luctus porttitor. Aenean blandit euismod sapien quis aliquam. Morbi mattis tortor laoreet metus auctor ultricies. Curabitur tincidunt ut nisl dapibus rutrum. Fusce ullamcorper augue in eros ullamcorper, id ullamcorper nibh venenatis. Proin eget molestie tellus, non gravida velit. Duis imperdiet efficitur arcu. Cras a nulla et sem feugiat ornare.

      Integer suscipit lorem aliquam est sollicitudin, ac finibus libero dignissim. Etiam rutrum a ex et malesuada. Donec vitae viverra urna. Morbi commodo, felis in malesuada convallis, nulla tortor consequat libero, vitae malesuada risus erat ac erat. Proin est nisl, vulputate vel convallis sed, dictum non ligula. Cras viverra, justo vitae egestas feugiat, mi sem rutrum dolor, sit amet tempor augue purus eget urna. Maecenas vel quam id justo malesuada commodo. Nam sed pellentesque nisl, in posuere turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean varius volutpat turpis in aliquam. Nunc ut enim consectetur, semper nulla placerat, vulputate tellus.

      In sagittis metus velit, eget tempus ex ultrices ac. Maecenas faucibus orci et dolor dapibus iaculis. Aenean vulputate elementum ornare. Donec et lacus dictum quam ornare feugiat sit amet ac urna. Aenean blandit velit volutpat efficitur interdum. Quisque fringilla iaculis arcu porta laoreet. Nam vel nibh non tellus tincidunt consequat ac ac nulla. Sed sit amet rhoncus nisl, fermentum auctor enim. Vivamus a elementum justo, vitae molestie justo. Vivamus suscipit leo eros, semper sagittis turpis molestie eu. Praesent vel egestas nulla. Etiam hendrerit dictum congue. Curabitur luctus mauris at odio faucibus lacinia quis sit amet risus. Etiam id est facilisis, consequat arcu in, maximus orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

      Etiam consectetur aliquet mauris, pulvinar luctus leo consectetur vitae. Donec varius accumsan nulla, ut tempor elit dictum sit amet. Integer interdum condimentum magna placerat blandit. Integer pulvinar, nisi sit amet ullamcorper imperdiet, est tortor vulputate orci, ut interdum neque arcu eu elit. Fusce at aliquam tortor, lacinia dictum felis. Pellentesque ut varius erat. Etiam ultrices lorem enim. Donec nibh tortor, fringilla ac libero ac, eleifend accumsan velit. Nullam non purus est. Sed feugiat et nisl ac maximus. Proin quis commodo neque, sed volutpat dolor. Phasellus sit amet odio aliquet, tincidunt purus et, cursus nisi.

      Pellentesque eu enim vel lacus accumsan scelerisque. Suspendisse pulvinar in magna vel rhoncus. Fusce purus erat, viverra non mattis vel, porta ut risus. Donec aliquam neque sed commodo rutrum. Curabitur elementum elit at dui molestie, vitae gravida libero vestibulum. Nunc mollis bibendum elit, id placerat massa consequat sit amet. Mauris vitae mi lacus. Phasellus at metus enim. Aliquam rutrum diam in eros varius, ut suscipit ante venenatis. Phasellus ut varius diam. In a dignissim mauris. Sed lacinia libero quam, at tempor leo feugiat sit amet. Curabitur accumsan tellus at quam facilisis tincidunt. Etiam consectetur faucibus viverra. Nullam at urna vel quam convallis convallis at nec est.

      Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc nec posuere nulla, ac ornare eros. Nullam in faucibus nulla, eu vulputate turpis. Vivamus dignissim fermentum lectus, eget aliquam tellus. Phasellus sapien risus, aliquet eget mollis sit amet, feugiat at enim. Sed vel orci a mauris congue bibendum. Nullam est magna, suscipit sit amet elementum molestie, mattis sit amet purus. Sed quis lorem euismod, euismod metus eget, mollis erat. Ut eget pulvinar lacus, sit amet dapibus mi.
    </p>
  </div>
</template>
